export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const FILTER_PRICE = "FILTER_PRICE ";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const DETAIL_PRODUCTS = "DETAIL_PRODUCTS";
export const FILTER_DISCOUNT = "FILTER_DISCOUNT"
export const FILTER_MODEL = "FILTER_MODEL"