export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const DETAIL_PRODUCTS = "DETAIL_PRODUCTS";
